import {createAction} from '../creators'

export default {
  ...createAction('FETCH_ACTIVITY', 'userId'),
  ...createAction('COMPLETE_FETCH_ACTIVITY', 'data'),
  ...createAction('FETCH_ALLACTIVITY', 'formData'),
  ...createAction('COMPLETE_FETCH_ALLACTIVITY', 'formData'),
  ...createAction('FETCH_REWARDS', 'formData'),
  ...createAction('COMPLETE_FETCH_REWARDS', 'formData'),
  ...createAction('FETCH_ABOUT', 'formData'),
  ...createAction('COMPLETE_FETCH_ABOUT', 'formData'),
  ...createAction('SEND_DOCUMENT', 'formData'),
  ...createAction('SEND_DOCUMENT_FAILED', 'formData'),
  ...createAction('SEND_DOCUMENT_SUCCESS', 'formData'),
  ...createAction('FETCH_DASHBORD', 'formData'),
  ...createAction('COMPLETE_FETCH_DASHBORD', 'formData'),
  ...createAction('FETCH_VENDORS', 'formData'),
  ...createAction('COMPLETE_FETCH_VENDORS', 'formData'),
  ...createAction('FETCH_CATEGORY', 'formData'),
  ...createAction('COMPLETE_FETCH_CATEGORY', 'formData'),
  ...createAction('GET_UPLOAD_DONE', 'data'),
  ...createAction('UPLOAD_PHOTO', 'field', 'data'),
  ...createAction('TAKE_AWARD', 'data'),
  ...createAction('COMPLETE_TAKE_AWARD', 'formData'),
  ...createAction('GET_POINTS', 'userId'),
  ...createAction('GET_POINTS_DONE', 'points'),
  ...createAction('FETCH_ACTIVITY_CATEGORY', 'formData'),
  ...createAction('COMPLETE_FETCH_ACTIVITY_CATEGORY', 'formData'),
}
